version: "3.3"

services:
  web:
    build: ./backend
    volumes:
      - ./backend/CalendarProject/CalendarProject:/mr_houssem/CalendarProject/CalendarProject
      - ./backend/CalendarProject/authen:/mr_houssem/CalendarProject/authen
    ports:
      - "8000:8000"
